language: rust
rust: nightly
services: docker

matrix:
  include:
    - name: "Tools"
      script: sh ci/tools.sh
    - name: "x86_64-unknown-linux-gnu"
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-apple-darwin"
      env: TARGET=x86_64-apple-darwin
      os: osx
      osx_image: xcode10
    - name: "x86_64-pc-windows-msvc"
      env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - name: "i686-apple-darwin"
      env: TARGET=i686-apple-darwin
      os: osx
      osx_image: xcode10

script: sh ci/run.sh $TARGET
